%%% logical-sweep-1 1u9fci78 %%%
Traced<ShapedArray(float32[3])>with<DynamicJaxprTrace(level=1/0)>
Traceback (most recent call last):
  File "C:\Users\31614\Documents\AI_course_stuff\RLForaging Thesis\RLForagingAgents\RL-models\TD3\train_loops.py", line 107, in wandb_train_td3
    obs, state = jax.lax.cond(done, env.reset(key_reset, env_params), (obs, state))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\31614\anaconda3\Lib\site-packages\jax\_src\traceback_util.py", line 180, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\31614\anaconda3\Lib\site-packages\jax\_src\lax\control_flow\conditionals.py", line 301, in cond
    return _cond(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\31614\anaconda3\Lib\site-packages\jax\_src\lax\control_flow\conditionals.py", line 198, in _cond
    raise TypeError("lax.cond: true_fun and false_fun arguments should be callable.")
TypeError: lax.cond: true_fun and false_fun arguments should be callable.
